[package]
name = "listroutines"
version = "0.1.0"
authors = ["Lucas Morales <lucas@lucasem.com>"]

[dependencies]
itertools = "0.7.1"
rocket_codegen = "0.3.5"
rocket = "0.3.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
workerpool = "1.0"
